# Generated by Django 3.2.7 on 2022-05-07 06:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='servings',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=4, null=True),
        ),
    ]
