# Generated by Django 3.2.7 on 2022-05-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_items', '0003_auto_20220507_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='groceryitem',
            name='servings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
